import { SoftwareItem } from './types';

export const INITIAL_CATALOG: SoftwareItem[] = [
  // --- AI Software ---
  {
    id: 'ollama',
    name: 'Ollama',
    tagline: 'Run LLMs locally on your machine',
    description: 'Get up and running with large language models locally. Run Llama 3.3, DeepSeek-R1, Mistral, Gemma, and custom models with GPU acceleration and built-in API.',
    category: 'ai',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'bot',
    version: '0.5.8',
    lastUpdated: '2 days ago',
    license: 'MIT',
    website: 'https://ollama.com',
    downloadUrl: 'https://ollama.com/download/OllamaSetup.exe',
    wingetId: 'Ollama.Ollama',
    sizeEstimate: '75 MB',
    featured: true,
    tags: ['AI', 'LLM', 'Local AI', 'DeepSeek', 'Llama'],
    releaseNotes: 'Added enhanced context window support and DeepSeek-R1 70B quantization support.',
    verified: true,
  },
  {
    id: 'lm-studio',
    name: 'LM Studio',
    tagline: 'Visual UI & server for local AI models',
    description: 'Discover, download, and experiment with local LLMs on your PC. Complete with chat interface, model playground, and OpenAI-compatible local HTTP server.',
    category: 'ai',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'sparkles',
    version: '0.3.6',
    lastUpdated: '5 days ago',
    license: 'Freeware',
    website: 'https://lmstudio.ai',
    downloadUrl: 'https://releases.lmstudio.ai/windows/x64/latest/LM-Studio-Setup.exe',
    wingetId: 'ElementLabs.LMStudio',
    sizeEstimate: '110 MB',
    featured: true,
    tags: ['AI', 'GUI', 'Local Server', 'HuggingFace'],
    releaseNotes: 'Major speedups for multi-GPU inference and native markdown code formatting.',
    verified: true,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'The AI-first Code Editor',
    description: 'Built to make you extraordinarily productive, Cursor is a fork of VS Code with deep AI integration, multi-file codebase understanding, and automated terminal debugging.',
    category: 'ai',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'wand2',
    version: '0.45.6',
    lastUpdated: '1 day ago',
    license: 'Proprietary / Free tier',
    website: 'https://cursor.com',
    downloadUrl: 'https://downloader.cursor.sh/windows/nsis/x64',
    wingetId: 'Anysphere.Cursor',
    sizeEstimate: '135 MB',
    featured: true,
    tags: ['AI', 'Editor', 'Copilot', 'Agentic Coding'],
    releaseNotes: 'Introduced agent mode for autonomous background multi-file refactoring.',
    verified: true,
  },
  {
    id: 'jan',
    name: 'Jan',
    tagline: 'Open-source local ChatGPT alternative',
    description: 'An open-source, privacy-first desktop assistant that runs completely offline on your computer. Fully customizable with extensions and customizable system prompts.',
    category: 'ai',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'brain',
    version: '0.5.10',
    lastUpdated: '1 week ago',
    license: 'AGPL-3.0',
    website: 'https://jan.ai',
    downloadUrl: 'https://github.com/janhq/jan/releases/download/v0.5.10/jan-win-x64-0.5.10.exe',
    wingetId: 'Jan.Jan',
    sizeEstimate: '95 MB',
    featured: false,
    tags: ['AI', 'Open Source', 'Privacy', 'Offline'],
    releaseNotes: 'Faster model switching and customizable system templates.',
    verified: true,
  },
  {
    id: 'open-webui',
    name: 'Open WebUI',
    tagline: 'Extensible, feature-rich web UI for LLMs',
    description: 'User-friendly web UI designed to operate entirely offline. Supports Ollama and OpenAI-compatible APIs with RAG document chat, web search, and voice interactions.',
    category: 'ai',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'layout-grid',
    version: '0.5.4',
    lastUpdated: '3 days ago',
    license: 'MIT',
    website: 'https://openwebui.com',
    downloadUrl: 'https://github.com/open-webui/open-webui/archive/refs/heads/main.zip',
    wingetId: '',
    sizeEstimate: '45 MB',
    featured: false,
    tags: ['AI', 'Web UI', 'RAG', 'Ollama Companion'],
    releaseNotes: 'Added hybrid vector search for attached code files and markdown preview improvements.',
    verified: true,
  },

  // --- Compilers & Assemblers ---
  {
    id: 'gcc-mingw',
    name: 'GCC / MinGW-w64',
    tagline: 'The GNU Compiler Collection for Windows',
    description: 'Essential compilation toolchain providing GCC, G++, GDB debugger, and Make utilities. The gold standard for compiling high-performance C and C++ programs.',
    category: 'compiler',
    platforms: ['windows'],
    iconType: 'binary',
    version: '14.2.0',
    lastUpdated: '2 weeks ago',
    license: 'GPLv3',
    website: 'https://www.mingw-w64.org',
    downloadUrl: 'https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.1-12.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.1-mingw-w64ucrt-12.0.0-r2.zip',
    wingetId: 'BrechtSanders.WinLibs.POSIX.UCRT',
    sizeEstimate: '85 MB',
    featured: true,
    tags: ['Compiler', 'C', 'C++', 'Toolchain', 'Make'],
    releaseNotes: 'Upgraded to GCC 14.2 with C++23 standards support and UCRT runtime integration.',
    verified: true,
  },
  {
    id: 'llvm-clang',
    name: 'LLVM / Clang',
    tagline: 'Modern, modular C/C++ compiler infrastructure',
    description: 'High-performance compiler front-end for C, C++, and Objective-C. Known for lightning-fast compilation, expressive diagnostics, and clang-format / clang-tidy tools.',
    category: 'compiler',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'terminal',
    version: '19.1.7',
    lastUpdated: '4 days ago',
    license: 'Apache-2.0 with LLVM Exception',
    website: 'https://llvm.org',
    downloadUrl: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-win64.exe',
    wingetId: 'LLVM.LLVM',
    sizeEstimate: '260 MB',
    featured: true,
    tags: ['Compiler', 'Clang', 'LLVM', 'C++', 'Diagnostics'],
    releaseNotes: 'Enhanced AVX-512 optimizations and updated clang-tidy diagnostics.',
    verified: true,
  },
  {
    id: 'nasm',
    name: 'NASM (Netwide Assembler)',
    tagline: 'The portable 80x86 and x86-64 assembler',
    description: 'Industry-standard open-source modular assembler designed for portability and speed. Widely used for low-level systems programming, OS kernels, and reverse engineering.',
    category: 'compiler',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'cpu',
    version: '2.16.03',
    lastUpdated: '1 month ago',
    license: 'BSD-2-Clause',
    website: 'https://www.nasm.us',
    downloadUrl: 'https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-installer-x64.exe',
    wingetId: 'NASM.NASM',
    sizeEstimate: '5 MB',
    featured: false,
    tags: ['Assembler', 'Assembly', 'x86_64', 'Low Level'],
    releaseNotes: 'Fixed macro expansion edge cases in 64-bit address mode.',
    verified: true,
  },
  {
    id: 'zig',
    name: 'Zig Compiler & Toolchain',
    tagline: 'Simple, fast, robust systems programming',
    description: 'A modern general-purpose language with zero hidden control flow, compile-time code execution, and a drop-in C/C++ cross-compiler (`zig cc`).',
    category: 'compiler',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'zap',
    version: '0.13.0',
    lastUpdated: '3 weeks ago',
    license: 'MIT',
    website: 'https://ziglang.org',
    downloadUrl: 'https://ziglang.org/download/0.13.0/zig-windows-x86_64-0.13.0.zip',
    wingetId: 'zig.zig',
    sizeEstimate: '42 MB',
    featured: true,
    tags: ['Compiler', 'Zig', 'Systems', 'C-Replacement'],
    releaseNotes: 'Incremental compiler improvements and expanded WebAssembly target features.',
    verified: true,
  },

  // --- Runtimes & SDKs ---
  {
    id: 'python',
    name: 'Python 3',
    tagline: 'The leading language for AI, data, and web',
    description: 'Python is an interpreted, high-level programming language that powers the worldwide AI explosion (PyTorch, TensorFlow, Pandas) and modern web services.',
    category: 'runtime',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'code-xml',
    version: '3.13.1',
    lastUpdated: '1 week ago',
    license: 'PSF License',
    website: 'https://www.python.org',
    downloadUrl: 'https://www.python.org/ftp/python/3.13.1/python-3.13.1-amd64.exe',
    wingetId: 'Python.Python.3.13',
    sizeEstimate: '26 MB',
    featured: true,
    tags: ['Runtime', 'Python', 'AI', 'pip', 'Data Science'],
    releaseNotes: 'Experimental free-threaded mode (no-GIL) and enhanced REPL with multiline editing.',
    verified: true,
  },
  {
    id: 'nodejs',
    name: 'Node.js (LTS)',
    tagline: 'JavaScript and TypeScript backend runtime',
    description: 'High-performance JavaScript runtime built on Chrome V8. Includes npm package manager to build APIs, fullstack React/Next.js apps, and developer tooling.',
    category: 'runtime',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'layers',
    version: '22.13.1',
    lastUpdated: '6 days ago',
    license: 'MIT',
    website: 'https://nodejs.org',
    downloadUrl: 'https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi',
    wingetId: 'OpenJS.NodeJS.LTS',
    sizeEstimate: '32 MB',
    featured: true,
    tags: ['Runtime', 'JavaScript', 'TypeScript', 'npm', 'Fullstack'],
    releaseNotes: 'Long-term support release with security fixes and V8 engine 12.4 update.',
    verified: true,
  },
  {
    id: 'rust',
    name: 'Rust & Cargo',
    tagline: 'Fast, reliable, and memory-safe language',
    description: 'Systems programming language that guarantees memory safety without garbage collection. Includes Cargo package manager and compiler toolchain.',
    category: 'runtime',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'shield-alert',
    version: '1.84.1',
    lastUpdated: '4 days ago',
    license: 'MIT / Apache-2.0',
    website: 'https://www.rust-lang.org',
    downloadUrl: 'https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe',
    wingetId: 'Rustlang.Rustup',
    sizeEstimate: '12 MB',
    featured: true,
    tags: ['Runtime', 'Rust', 'Cargo', 'Memory Safety', 'Performance'],
    releaseNotes: 'Stabilized standard library APIs and reduced incremental compilation times.',
    verified: true,
  },
  {
    id: 'golang',
    name: 'Go (Golang)',
    tagline: 'Open-source language for scalable cloud software',
    description: 'Fast, statically typed, compiled language engineered at Google. Famous for simple concurrency (goroutines), fast compilation, and cloud-native microservices.',
    category: 'runtime',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'box',
    version: '1.24.0',
    lastUpdated: '1 week ago',
    license: 'BSD-3-Clause',
    website: 'https://go.dev',
    downloadUrl: 'https://go.dev/dl/go1.24.0.windows-amd64.msi',
    wingetId: 'GoLang.Go',
    sizeEstimate: '115 MB',
    featured: false,
    tags: ['Runtime', 'Go', 'Backend', 'Concurrency', 'Microservices'],
    releaseNotes: 'Introduced tool directives in go.mod and improved memory allocator efficiency.',
    verified: true,
  },
  {
    id: 'openjdk',
    name: 'OpenJDK Java (Temurin)',
    tagline: 'Enterprise-grade Java SE development kit',
    description: 'Free and open-source implementation of Java Platform, Standard Edition. Powered by Eclipse Temurin, trusted by millions of enterprise developers.',
    category: 'runtime',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'coffee',
    version: '21.0.6',
    lastUpdated: '2 weeks ago',
    license: 'GPLv2+CE',
    website: 'https://adoptium.net',
    downloadUrl: 'https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.6%2B7/OpenJDK21U-jdk_x64_windows_hotspot_21.0.6_7.msi',
    wingetId: 'EclipseAdoptium.Temurin.21.JDK',
    sizeEstimate: '190 MB',
    featured: false,
    tags: ['Runtime', 'Java', 'JVM', 'Kotlin', 'Spring'],
    releaseNotes: 'Quarterly security maintenance update and performance patches.',
    verified: true,
  },

  // --- IDEs & Code Editors ---
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    tagline: 'Code editing, redefined',
    description: 'The standard modern code editor. Features built-in Git, debugging, intelligent code completion with IntelliSense, and an ecosystem of tens of thousands of extensions.',
    category: 'ide',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'file-code-2',
    version: '1.97.2',
    lastUpdated: '3 days ago',
    license: 'Freeware / Source MIT',
    website: 'https://code.visualstudio.com',
    downloadUrl: 'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user',
    wingetId: 'Microsoft.VisualStudioCode',
    sizeEstimate: '95 MB',
    featured: true,
    tags: ['IDE', 'Editor', 'Microsoft', 'Extensions', 'TypeScript'],
    releaseNotes: 'Enhanced multi-cursor selection, inline chat improvements, and terminal split view.',
    verified: true,
  },
  {
    id: 'zed',
    name: 'Zed Editor',
    tagline: 'High-performance, multiplayer code editor',
    description: 'Engineered in Rust to harness every core of your CPU and GPU. Near zero input latency, native AI assistant integration, and effortless real-time collaboration.',
    category: 'ide',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'sparkle',
    version: '0.174.4',
    lastUpdated: '1 day ago',
    license: 'GPL-3.0 / Apache-2.0',
    website: 'https://zed.dev',
    downloadUrl: 'https://zed.dev/api/releases/stable/latest/download?asset=Zed-x86_64.msi',
    wingetId: 'Zed.Zed',
    sizeEstimate: '65 MB',
    featured: true,
    tags: ['IDE', 'Rust', 'Ultra Fast', 'AI', 'Multiplayer'],
    releaseNotes: 'Windows stability overhaul and native terminal rendering speed boost.',
    verified: true,
  },
  {
    id: 'neovim',
    name: 'Neovim',
    tagline: 'Hyperextensible Vim-based text editor',
    description: 'Rebuilding Vim for the 21st century. Features native LSP (Language Server Protocol), asynchronous job control, treesitter syntax trees, and first-class Lua scripting.',
    category: 'ide',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'terminal',
    version: '0.10.3',
    lastUpdated: '2 weeks ago',
    license: 'Apache-2.0',
    website: 'https://neovim.io',
    downloadUrl: 'https://github.com/neovim/neovim/releases/latest/download/nvim-win64.zip',
    wingetId: 'Neovim.Neovim',
    sizeEstimate: '28 MB',
    featured: false,
    tags: ['IDE', 'Vim', 'Terminal', 'Lua', 'LSP'],
    releaseNotes: 'Added diagnostic highlights improvements and tree-sitter queries cleanup.',
    verified: true,
  },
  {
    id: 'pycharm-ce',
    name: 'PyCharm Community',
    tagline: 'Dedicated IDE for Python programming',
    description: 'Intelligent code inspection, on-the-fly error detection, quick-fixes, smart navigation, and integrated debugger designed specifically for Python development.',
    category: 'ide',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'code',
    version: '2024.3.2',
    lastUpdated: '1 week ago',
    license: 'Apache-2.0',
    website: 'https://www.jetbrains.com/pycharm/',
    downloadUrl: 'https://download.jetbrains.com/python/pycharm-community-2024.3.2.exe',
    wingetId: 'JetBrains.PyCharm.Community',
    sizeEstimate: '620 MB',
    featured: false,
    tags: ['IDE', 'Python', 'JetBrains', 'Debugger'],
    releaseNotes: 'Enhanced support for Python 3.13 type variables and virtualenv detection.',
    verified: true,
  },

  // --- Developer Utilities & Tools ---
  {
    id: 'git',
    name: 'Git for Windows',
    tagline: 'Fast, distributed version control system',
    description: 'The foundation of modern software engineering. Package includes Git command-line tools, Git Bash terminal environment, and Git GUI.',
    category: 'tool',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'git-branch',
    version: '2.48.1',
    lastUpdated: '5 days ago',
    license: 'GPLv2',
    website: 'https://git-scm.com',
    downloadUrl: 'https://github.com/git-for-windows/git/releases/latest/download/Git-64-bit.exe',
    wingetId: 'Git.Git',
    sizeEstimate: '62 MB',
    featured: true,
    tags: ['Tool', 'Git', 'VCS', 'CLI', 'GitHub'],
    releaseNotes: 'Latest security fixes and updated MinTTY terminal in Git Bash.',
    verified: true,
  },
  {
    id: 'docker-desktop',
    name: 'Docker Desktop',
    tagline: 'Build, share, and run containerized apps',
    description: 'Seamless container engine integration with WSL2 backend on Windows. Includes Docker Engine, Docker CLI client, Docker Compose, Docker Scout, and Kubernetes.',
    category: 'tool',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'container',
    version: '4.38.0',
    lastUpdated: '1 week ago',
    license: 'Freeware / Commercial for Enterprise',
    website: 'https://www.docker.com/products/docker-desktop/',
    downloadUrl: 'https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe',
    wingetId: 'Docker.DockerDesktop',
    sizeEstimate: '540 MB',
    featured: true,
    tags: ['Tool', 'Containers', 'Docker', 'WSL2', 'Kubernetes'],
    releaseNotes: 'Resource Saver mode auto-throttles memory when idle, reducing laptop battery drain.',
    verified: true,
  },
  {
    id: 'beekeeper-studio',
    name: 'Beekeeper Studio',
    tagline: 'Modern and easy-to-use SQL editor',
    description: 'Intuitive database management app with tabbed SQL query runner, schema designer, and table data editor. Supports PostgreSQL, MySQL, SQLite, and SQL Server.',
    category: 'tool',
    platforms: ['windows', 'mac', 'linux'],
    iconType: 'database',
    version: '5.0.8',
    lastUpdated: '2 weeks ago',
    license: 'GPLv3 / Open Source',
    website: 'https://www.beekeeperstudio.io',
    downloadUrl: 'https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v5.0.8/Beekeeper-Studio-Setup-5.0.8.exe',
    wingetId: 'BeekeeperStudio.BeekeeperStudio',
    sizeEstimate: '85 MB',
    featured: false,
    tags: ['Tool', 'SQL', 'Database', 'Postgres', 'SQLite'],
    releaseNotes: 'Added SQLite full-text search preview and visual foreign key relationship graph.',
    verified: true,
  },
  {
    id: 'windows-terminal',
    name: 'Windows Terminal',
    tagline: 'Modern, fast terminal application',
    description: 'High-performance GPU-accelerated terminal for command-line users. Supports tabs, panes, Unicode text, emojis, custom themes, and SSH integration.',
    category: 'tool',
    platforms: ['windows'],
    iconType: 'terminal-square',
    version: '1.22.3232.0',
    lastUpdated: '1 week ago',
    license: 'MIT',
    website: 'https://github.com/microsoft/terminal',
    downloadUrl: 'https://github.com/microsoft/terminal/releases/download/v1.22.3232.0/Microsoft.WindowsTerminal_Win10_1.22.3232.0_8wekyb3d8bbwe.msixbundle',
    wingetId: 'Microsoft.WindowsTerminal',
    sizeEstimate: '38 MB',
    featured: false,
    tags: ['Tool', 'Terminal', 'PowerShell', 'WSL', 'CMD'],
    releaseNotes: 'Rendering speed optimizations and custom title bar customization.',
    verified: true,
  },
];
